--liquibase formatted sql

--changeset rsaraphael:02

ALTER TABLE ITINERARY ADD COLUMN PILOT_ID integer;
ALTER TABLE ITINERARY ADD COLUMN AIRCRAFT_ID integer;
ALTER TABLE ITINERARY ADD COLUMN FLIGHT_ID integer;
ALTER TABLE ITINERARY ADD FOREIGN KEY(PILOT_ID) REFERENCES PILOT(ID);
ALTER TABLE ITINERARY ADD FOREIGN KEY(AIRCRAFT_ID) REFERENCES AIRCRAFT(ID);
ALTER TABLE ITINERARY ADD FOREIGN KEY(FLIGHT_ID) REFERENCES FLIGHT(ID);


ALTER TABLE FLIGHT ADD COLUMN ORIGIN integer;
ALTER TABLE FLIGHT ADD COLUMN DESTINATION integer;
ALTER TABLE FLIGHT ADD FOREIGN KEY(ORIGIN) REFERENCES LOCATION(ID);
ALTER TABLE FLIGHT ADD FOREIGN KEY(DESTINATION) REFERENCES LOCATION(ID);