--liquibase formatted sql

--changeset rsaraphael:02

ALTER TABLE FLIGHT ADD COLUMN ITINERARY_ID integer;
ALTER TABLE FLIGHT ADD COLUMN AIRCRAFT_ID integer;
ALTER TABLE FLIGHT ADD COLUMN PILOT_ID integer;
ALTER TABLE ITINERARY ADD COLUMN CITY_ID integer;

ALTER TABLE FLIGHT ADD FOREIGN KEY(AIRCRAFT_ID) REFERENCES AIRCRAFT(ID);
ALTER TABLE FLIGHT ADD FOREIGN KEY(ITINERARY_ID) REFERENCES ITINERARY(ID);
ALTER TABLE FLIGHT ADD FOREIGN KEY(PILOT_ID) REFERENCES PILOT(ID);
ALTER TABLE ITINERARY ADD FOREIGN KEY(CITY_ID) REFERENCES CITY(ID);